### ISSUE TITLE
do not pin opentelemetry-* dependencies

### ISSUE THREAD

**Issue by thomasleveil** [uptrace/uptrace-python#119]
Currently, it is not possible to install `uptrace==1.10.1` alongside with `opentelemetry-instrumentation-requests==0.30b1`. 

The conflicts is that opentelemetry-instrumentation-requests requires `opentelemetry-api~=1.3` while this project [requires `opentelemetry-api==1.11.1`](https://github.com/uptrace/uptrace-python/blob/master/setup.cfg#L30)

**Comment by vmihailenco** [comment]
Thanks for the report. I've committed a change that does not pin the opentelemetry-api version any more - https://github.com/uptrace/uptrace-python/blob/master/setup.cfg#L30 . I guess we still need to pin the SDK, because OpenTelemetry still does incompatible changes there...

And I've also released v1.11.1 - please let me know how that works.

**Comment by thomasleveil** [comment]
Thank you for such a fast update. You rule !
Installation now works in my project
